name: paccmann_predictor2
channels:
 - https://conda.anaconda.org/rdkit
dependencies:
  - rdkit=2019.03.1
  - python>=3.6,<3.8
  - pip>=19.1
  - pip:
    # - pytoda @ git+https://github.com/PaccMann/paccmann_datasets@0.0.3
    - pytoda @ git+https://github.com/gihanpanapitiya/paccmann_datasets@to_candle
    - candle @ git+https://github.com/ECP-CANDLE/candle_lib@develop
    - numpy>=1.14.3
    - scipy>=1.3.1
    - torch==1.13.0
